name: Build and Push Releases

on:
  release:
    types: [ published ]

jobs:
  update-registry:
    name: Update Registry Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to git.beans.team
        uses: docker/login-action@v3
        with:
          registry: git.beans.team
          username: em
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: git.beans.team/em/scouter:${{ github.event.release.tag_name }}
